DEBUG 2021-12-22 14:57:11.184 UTC: 	 CRAB Client version: v3.211130
DEBUG 2021-12-22 14:57:11.184 UTC: 	 Running on: Linux lxplus792.cern.ch 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-12-22 14:57:11.184 UTC: 	 Executing command: 'status'
DEBUG 2021-12-22 14:57:11.185 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/mikumar/.crab3
ERROR 2021-12-22 14:57:11.188 UTC: 	 Error: crab_Run2016H_mu_Minitree_2J1T0_2016/ is not a valid CRAB project directory.
ERROR 2021-12-22 14:57:11.188 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 149, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/bin/crab.py", line 134, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/status.py", line 47, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 269, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.211130.01/lib/CRABClient/Commands/SubCommand.py", line 636, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_Run2016H_mu_Minitree_2J1T0_2016/ is not a valid CRAB project directory.
INFO 2021-12-22 14:57:11.192 UTC: 	 Log file is /afs/cern.ch/work/m/mikumar/private/NanoAOD_new/CMSSW_10_6_0/src/PhysicsTools/NanoAODTools/crab/tree/crab.log
